# Specify a non-default branch for pull requests for composer dependencies

version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
    # Raise pull requests for version updates
    # to composer packages against the `development` branch
    target-branch: "development"
    # Labels on pull requests for version updates
    labels:
      - "composer dependencies"
